### ISSUE TITLE
Ideas for different face mask

### ISSUE THREAD

**Issue by shubhamji88** [ACM-VIT/SparkAR-Creators#19]
here i have uploaded the different mask i have created in order to use it as face mask in spark AR..
all the ideas which i got, these can be directly used on the face mesh as texture

**Comment by lopeselio** [comment]
would be very helpful

**Comment by lopeselio** [comment]
We are open to more contributions for this issue.

**Comment by lopeselio** [comment]
#21 merged

**Comment by lopeselio** [comment]
We're open to more textures for face masks.
