### ISSUE TITLE
Filter of Magician Dog

### ISSUE THREAD

**Issue by shubhamji88** [ACM-VIT/SparkAR-Creators#22]
You can tap screen to change the mask,
this filter has used particle system to give the magic effect around the stick
lighten the person a bit
![dogCapture](https://user-images.githubusercontent.com/56815364/95678044-684a9000-0be7-11eb-8966-2fe8438d0d24.PNG)

**Comment by lopeselio** [comment]
@shubhamji88  Can we know the size of the effect?

**Comment by lopeselio** [comment]
@shubhamji88  Make sure you create a PR, we will suggest chnages if needed. Also add your details here:
https://github.com/ACM-VIT/SparkAR-Creators/blob/master/Contributing.md

**Comment by shubhamji88** [comment]
Older Android 3.83 MB...for android and ios its just calculating the file size  form last 30 min

**Comment by shubhamji88** [comment]
Android : 2.06MB
IOS: 2.16 MB

**Comment by lopeselio** [comment]
@shubhamji88  alright that's cool ! #24 PR merged
