### ISSUE TITLE
3-L2A Submission-Shriyashish Mishra

### ISSUE THREAD

**Issue by shriyashish** [ACM-VIT/SparkAR-Creators#6]
3-L2A Submission-Shriyashish Mishra-- Have added the link below, kindly accept.
https://github.com/ACM-VIT/SparkAR-Creators/pull/5

**Comment by lopeselio** [comment]
noted!

**Comment by lopeselio** [comment]
https://github.com/ACM-VIT/SparkAR-Creators/pull/5
The effect has been approved for the hackathon and the PR has been merged
  #hactoberfest-merged
