### ISSUE TITLE
We're looking to make an effect with a moving 3D human figure. The 3D object should be rigged in Blender. We are looking for 3D assets for the same. Animations can include walking, dancing, jumping or any other actions.

### ISSUE THREAD

**Issue by lopeselio** [ACM-VIT/SparkAR-Creators#7]
- [x] Need 3D assets
- [x] Audio asset for supporting the animation 
- [x] Create a scene involving the moving 3D object
- [x] This effect would be published on Instagram. Make sure the project is less than 5MB
- [x] You are free to use patches or scripts

Please mention your ideas in the comments on the issue. Share the links to assets(audio, video, 3D, textures) in the comments so that we can approve and merge your contributions to the project.

**Comment by rosy-02** [comment]
Hey there, I have a rigged human figure along with a moving animation in made with blender.

**Comment by rosy-02** [comment]
@rosy-02  create a pull request with your submission. We will see it and merge if that's fine.

**Comment by rosy-02** [comment]
We can use an ancient arabic audio, the animation is exported from Blender. And a simple texture in the hackground to create a scene.

**Comment by rosy-02** [comment]
Mightn't use patches or scripts for the same.

**Comment by lopeselio** [comment]
Merged https://github.com/ACM-VIT/SparkAR-Creators/pull/17 from @rosy-02. More projects invited.

**Comment by lopeselio** [comment]
Issue closed
